README.md, src/Test/QuickCheck.purs
=> Add Arb/CoArb instances for Unit and Ordering

src/Test/QuickCheck/Arbitrary.purs, src/Test/QuickCheck/Gen.purs
The Arbitrary Array instance now depends on the Gen's size parameter; if
the size is n, then the number of elements in a generated array should
be equally likely to be any number from 0 up to n-1.
This also fixes #35, a bug where vectorOf 0 x would contain exactly 2
elements rather than 0. This needed to be fixed to ensure that an
`arbitrary :: Gen (Array a)` is capable of producing empty arrays.
=> Better Arbitrary Array instance

docs/Test/QuickCheck.md, docs/Test/QuickCheck/Gen.md, docs/Test/QuickCheck/LCG.md, src/Test/QuickCheck.purs, src/Test/QuickCheck/Gen.purs, src/Test/QuickCheck/LCG.purs
Refs #32, /cc @sharkdp
This commit uses the same parameters as C++11's `minstd_rand`, which has a
much smaller multiplier, meaning that faults due to bad precision are
~~much less likely~~ no longer possible. *edit: The largest possible value
for the seed is the modulus, `2^31 - 1`, and multiplying this by the new
multiplier gives the correct result.*
Also, I modified the sampling API exported by Test.QuickCheck.Gen. Now
that psci supports printing stuff to the console, returning the actual
values seems more useful (as you can do stuff with them, like summing an
array of numbers, for example).
An example with the new parameters:
> map sum $ randomSample' 5000 $ chooseInt 0 2
2533
=> Adjust LCG parameters

bower.json, docs/Test/QuickCheck/Gen.md, src/Test/QuickCheck/Gen.purs, test/Main.purs
Refs #30, #29. Use `tailrec` to make `vectorOf` stack safe. Also export `listOf`, which will probably be useful.
Although `vectorOf` is now stack safe, `replicateM` will still overflow for a sufficiently large size. Perhaps `replicateMRec` should go into `tailrec`, and then we could direct people to use `replicateMRec` where necessary?
Alternatively, the formulation in #30 based on `Trampoline` doesn't have this problem. I haven't been able to find a way to make the `Trampoline` version stack overflow, even with `replicateM`. (@jdegoes, can you think of an example that might?)
=> Stack safe gen (StateT)

src/Test/QuickCheck/Arbitrary.purs
We may as well provide these since QC depends on them anyway.
=> Add Arb/Coarb instances for all data dependencies

docs/Test/QuickCheck.md, docs/Test/QuickCheck/Arbitrary.md, docs/Test/QuickCheck/Data/AlphaNumString.md, docs/Test/QuickCheck/Data/ApproxNumber.md, docs/Test/QuickCheck/Gen.md, docs/Test/QuickCheck/LCG.md, src/Test/QuickCheck/Gen.purs, src/Test/QuickCheck/LCG.purs
This fixes an issue with `repeatable` which basically made all tests for HOFs equivalent :scream:
=> Fix 'repeatable'

src/Test/QuickCheck.purs, src/Test/QuickCheck/Data/AlphaNumString.purs, src/Test/QuickCheck/LCG.purs
=> Prepare for 2.0 release (sans shrinking)

bower.json, src/Test/QuickCheck/Arbitrary.purs, src/Test/QuickCheck/Data/AlphaNumString.purs, src/Test/QuickCheck/Gen.purs
We introduce a dependency on `purescript-nonempty` and use the provided type wherever it is called for.
=> [BREAKING] Use NonEmpty

src/Test/QuickCheck/Gen.purs
Fixes #71 
Please read the issue above for more details on the problem.
This is the most conservative, non-breaking fix to the issue I could think of. It basically does what we were doing before, but converts the `Int`s to `Number`s to work its magic, and steps the LCG twice in order to hide a 32 bit `Int` inside a `Number`.
The branch here has a very simple test you can run with `pulp test` to see that it does indeed work: https://github.com/matthewleon/purescript-quickcheck/tree/test-chooseInt32
=> let chooseInt work with differences greater than 2^31

bower.json, src/Test/QuickCheck/Arbitrary.purs, test/Main.purs
Someone in IRC was asking about these a little while ago, I thought it was a good idea to have them. Thoughts?
=> Add genericArbitrary and genericCoarbitrary

bower.json, src/Test/QuickCheck/Arbitrary.purs, test/Main.purs
This adds an `Arbitrary` instance for general records:
Example
``` purs
type Person =
{ name :: { first :: String
, last :: String
}
, age :: Int
, height :: Number
}
> persons ← randomSample' 10 (arbitrary :: Gen Person)
```
*Note*: This is the first time that I'm using the new (and awesome) typelevel-programming features of PureScript, so I'm not sure if I'm doing this correctly :smile:
=> Add 'Arbitrary' instance for records

bower.json, src/Test/QuickCheck/Arbitrary.purs
Arbitrary and Coarbitrary for NonEmptyArray and NonEmptyString.
fixes https://github.com/purescript/purescript-quickcheck/issues/90
=> Arbitrary instances for NonEmpty*

src/Test/QuickCheck.purs
Resolves #47 
The formulation here is a little different though, as you don't actually need to split the generator and test the way that was suggested in the issue, since you can write it in the generator directly:
``` purescript
forAll do
m <- maps :: Gen (Map Int String))
pure $ m == Map.fromUnfoldable (Map.toFoldable m)
```
Since that issue was opened, `MonadGen` has come into existence, and with it I've given up using `Arbitrary` at all, the only problem is you can't throw `MonadGen` constrained things directly into `quickcheck`, as it doesn't know what to instantiate the `MonadGen m` with. These `forAll` varieties solve that.
/cc @hdgarrood
=> Add `quickCheckGen` and variants

src/Test/QuickCheck/Gen.purs
=> Add generate

src/Test/QuickCheck/Arbitrary.purs
`coarbitrary` is intended to perturb an unrelated `Gen` with data that implements the typeclass - it's not intended to be explicitly related to the generated data.
=> fixing genericCoarbitrary

src/Test/QuickCheck/Arbitrary.purs, src/Test/QuickCheck/Gen.js, src/Test/QuickCheck/Gen.purs
The issue doesn’t suggest to replace `NonEmpty List` by `NonEmptyList` in `frequency` but I thought it would be better for consistency. I’m happy to revert that if isn’t wanted.
Close https://github.com/purescript/purescript-quickcheck/issues/109.
=> Replace NonEmpty Array and NonEmpty List by NonEmptyArray and NonEmptyList

CHANGELOG.md
This PR updates the CHANGELOG in preparation for the upcoming release of this library.
Related: purescript/purescript#3985
=> Updated changelog since v6.1.0

CHANGELOG.md, src/Test/QuickCheck/Gen.purs
Self explanatory. Backlinking to purescript/purescript#4071
---
**Checklist:**
=> Fix warnings revealed by v0.14.1 PS release; export functions

src/Test/QuickCheck/Arbitrary.purs
I didn't include Endo because it would take more time for me to figure out what it should be. The others are pretty obvious, so I just did those.
=> Add arbitrary instances for newtypes in Prelude

CHANGELOG.md, src/Test/QuickCheck.purs, test/Main.purs
Fixes https://github.com/purescript/purescript-quickcheck/issues/126
I used `tailRec` similar to how `quickCheckWithSeed` does.
---
**Checklist:**
=> stack safety for quickCheckPure and quickCheckPure'

CHANGELOG.md, src/Test/QuickCheck/Gen.purs
=> Use NonEmptyArray rather than NEL for frequency

CHANGELOG.md, src/Test/QuickCheck/Arbitrary.purs
Replace polymorphic proxy with monomorphic one
---
**Checklist:**
=> Fix forall proxy workaround
